CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
This resolves order import failures for orders that contain Shopgate coupons.
=> SHOPWARE-844

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Redirect.php, src/Backend/SgateShopgatePlugin/Models/Export/Product/Xml.php
=> SHOPWARE-842

src/Backend/SgateShopgatePlugin/Components/Redirect.php
fix redirect of homepage
code style
=> SHOPWARE-832

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Helpers/Attribute.php
fixed missing attributes in plugin configuration
=> Shopware 847

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> SHOPWARE-852

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php, tests/Bootstrap.php, tests/Unit/PluginTest.php
because of wrong assignment of payment methods
=> SHOPWARE-861: reverted latest changes in method getShopPaymentMethodName

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
Rainer,
Thanks for looking at this pull request.
Aaron
=> Shopware 874 wrong delivery time for all

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
set sCurrencyId and sCurrencyName, since i is set in frontend-checkout-getBasket method since version 5
=> SHOPWARE-878

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
Corrected two typos that prevented proper mapping of shipping methods to orders
=> Shopware 880 wrong shipping type mapping

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
use mode to distinguish between coupons and cart rule discounts
=> SHOPWARE-879

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> SHOPWARE-887

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> SHOPWARE-894: fixed add order error with missing currency factor

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Plugin.php
=> Shopware 893 coupon amount is wrong

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Settings.php
=> SHOPWARE-899

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
=> Shopware 906 no product images exported

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> SHOPWARE-933: fixed add_order fail caused by customer number mismatch

src/Backend/SgateShopgatePlugin/Plugin.php
=> Shopware 933 add order database error insertordercustomer

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
=> SHOPWARE-948: improved fetching attributes during exports

CHANGELOG.md, composer.json, composer.lock, src/Backend/SgateShopgatePlugin/Bootstrap.php
=> Shopware 954 missing htaccess file

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> Shopware 958 add order error call to a member

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> also map PayPal order to SwagPaymentPayPalUnified

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Redirect.php
fixed potential security issue in redirect
=> SHOPWARE-974 fix potential security issue in redirect

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
=> SHOPWARE-977 export related and similar products just with their id

.travis.yml
Update of the dependency checker
=> use new release of the php dependency checker

.travis.yml, CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Plugin.php
=> SHOPWARE-983 replace deprecated version constants

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
=> PI-9685 - fix order debit payment method for SW >= 5.0

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Import/Customer.php
Invalid countries resulted in a fatal php error.
=> Shopware 991 shopware exception

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Models/Import/Customer.php
Added the missing session object in the user component. The pricing for customer groups and shipping returns the right amount.
=> Bug fix login, shipping and customer groups pricing

src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Components/Address.php, src/Backend/SgateShopgatePlugin/Components/Cart.php, src/Backend/SgateShopgatePlugin/Components/Favorites.php, src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php, src/Backend/SgateShopgatePlugin/Helpers/WebCheckout.php
Fix bug in older Shopware versions to save a new address.
Handle exception bug if advanced cart plugin is not installed.
Fix order tracking
=> Fix bugs in favorite and address list

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Address.php, src/Backend/SgateShopgatePlugin/Components/Cart.php, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Components/Favorites.php, src/Backend/SgateShopgatePlugin/Components/Settings.php, src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php, src/Backend/SgateShopgatePlugin/Helpers/WebCheckout.php, src/Backend/SgateShopgatePlugin/Models/Export/Product.php, src/Backend/SgateShopgatePlugin/Plugin.php
=> Shopware 993 compatibility with shopware 5.6

src/Backend/SgateShopgatePlugin/Components/Config.php
fix config init for some Shopware versions
=> Shopware 998 config cant be read

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Export.php
=> SHOPWARE-1006 fix customer group id fetching

CHANGELOG.md, release/build_release_package.sh, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Models/Export/Product/Xml.php
fix caching of customer groups
=> SHOPWARE-1008 fix caching of customer groups

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php
Added an option to consider the "always_select_payment" flag during checkout and redirect the user to the payment methods page if it has been set.
=> Added option to consider the "always_select_payment" flag during checkout

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Helpers/WebCheckout.php
=> Increased the JWT Token timeout from 60 seconds to 5 minutes

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Category.php
Fixed category image export for Shopware 5.6 and newer.
=> Shopware 1011 incorrect category image urls

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Plugin.php
Fixed missing article number for cart rule items in the order details.
=> SHOPWARE-1014: fixed missing article number for cart rules

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php, src/Backend/SgateShopgatePlugin/plugin.xml
Added support for bonus points and account/documents page
=> Added support for bonus points and account/documents page

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Views/frontend/index/index.tpl, src/Backend/SgateShopgatePlugin/plugin.xml
Call updateSession pipeline always when needed. Fix for empty cart after new session
=> Call updateSession pipeline always when needed. Fix for empty cart after new session

.gitignore, CHANGELOG.md, README.md, src/Backend/SgateShopgatePlugin/Models/Export/Category.php, src/Backend/SgateShopgatePlugin/Models/Export/Category/Xml.php, src/Backend/SgateShopgatePlugin/Models/Export/Product.php, src/Backend/SgateShopgatePlugin/Models/Export/Product/Xml.php, src/Backend/SgateShopgatePlugin/Plugin.php, src/Backend/SgateShopgatePlugin/plugin.xml
=> Multi shop view support

src/Backend/SgateShopgatePlugin/Plugin.php
Get shop scoped customer data via plugin get customer action.
=> Get scoped customer data via plugin get customer action

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Bootstrap.php
Improve recognition of in-app browser
=> identify app in checkout by user agent

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Cart.php
=> fix taxes in cart view

src/Backend/SgateShopgatePlugin/Components/Cart.php
export voucherCode. No changelog entry since this is a very technical detail
=> Sg 34 export real voucher code in get cart

.travis.yml, CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Cart.php
trigger payment method rules validation
=> trigger payment method rules validation

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Favorites.php
=> SG-43 reduce response size for getFavorites

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Cart.php
=> in cart validation: keep current shipping method, if it is still valid

src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php
Support for reviews and bewertungen page
=> Support for reviews and bewertungen page

src/Backend/SgateShopgatePlugin/Components/Favorites.php
fix favorite sync for Shopware 5.7
=> fix favorite sync for Shopware 5.7

src/Backend/SgateShopgatePlugin/Components/Cart.php, src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php
fix session problems, not tested with Shopware < 5.7
=> fix session problems, not tested with Shopware < 5.7

src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Plugin.php
=> Sg 60 failed login after registration

src/Backend/SgateShopgatePlugin/Components/Cart.php, src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php, src/Backend/SgateShopgatePlugin/Helpers/WebCheckout.php
=> make session handling compatible with Shopware 5.6 and lower again

src/Backend/SgateShopgatePlugin/Components/User.php, src/Backend/SgateShopgatePlugin/Views/frontend/index/index.tpl
=> fix registration for shops, which are not set up on a TDL directly

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
export of attributes with type Datetime
=> Fix for date time properties

src/Backend/SgateShopgatePlugin/Bootstrap.php, src/Backend/SgateShopgatePlugin/Components/Config.php
=> use paths according to Shopware 5 specifications

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Favorites.php, src/Backend/SgateShopgatePlugin/Controllers/Frontend/shopgate.php, src/Backend/SgateShopgatePlugin/Helpers/WebCheckout.php
=> SG-104 extend favorite endpoints to handle multiple wishlists

src/Backend/SgateShopgatePlugin/Components/Cart.php
=> SG-119 fix for item disappearing from wishlist

CHANGELOG.md, src/Backend/SgateShopgatePlugin/Models/Export/Product.php
=> export of regulation price

.gitignore, CHANGELOG.md, src/Backend/SgateShopgatePlugin/Components/Config.php, src/Backend/SgateShopgatePlugin/Components/Export.php, src/Backend/SgateShopgatePlugin/Models/Export/Product.php, src/Backend/SgateShopgatePlugin/Models/Export/Product/Xml.php, tests/Postman/collection.json, tests/README.md, tests/assets/500-s_core_pricegroups.sql, tests/assets/501-s_core_pricegroups_discounts.sql, tests/package.json
* Added a config to skip category export
* Added a config to skip advanced product export
* Made some initialization conditional based on whether the query is an export or not.
* Added test scenarios for activating/deactivating both settings & checking export data
=> SG-184 adjust performance of export
